### ISSUE TITLE
代码运行

### ISSUE THREAD

**Issue by 6868l** [BJTUSensor/CS_KSVD#1]
你好，我看了您的关于CS-SKVD论文，并且准备仿真复现一下结果，在运行中发现，里面的OMP函数和OMPerr（）函数没有在文件里，所以运行不想出来，小白跪求指导，感谢您了，感谢您百忙之中抽出时间看到这个问题。

**Comment by BJTUSensor** [comment]
您好，感谢关注，OMPerr函数没有用到。OMP函数可以参考[OMP.m](https://github.com/BJTUSensor/CS_KSVD/blob/main/OMP.m)，谢谢！
